NullptrException: Check if documentFile is null
This happens if we have permission for a Uri, but it doesn't
exist (maybe because it was removed behind the scenes).